var  winterBackground, tree1, desertbg, cactus, snowman, crystal, tree2, bush, city, char1, char2, char3, scene1, scene2, scene3, currentScene;

function setup() {
  createCanvas(800,800)
  winterBackground = createSprite(800,400)
  winterBackground.addImage(loadImage('sprites/BG1.png'))
  tree1 = createSprite(400,660,width/100,height/100)
  tree1.addImage(loadImage('sprites/tree_1.png'))
  snowman = createSprite(150,700,width/100,height/100)
  snowman.addImage(loadImage('sprites/SnowMan.png'))
  crystal = createSprite(660,760,width/100,height,100)
  crystal.addImage(loadImage('sprites/Crystal.png'))
  desertbg = createSprite(600,400,)
  desertbg.addImage(loadImage('sprites/BG.png'))
  cactus = createSprite(310,570,width/100,height/100)
  cactus.addImage(loadImage('sprites/Cactus1.png'))
  tree2 = createSprite(670,600,width/100,height/100)
  tree2.addImage(loadImage('sprites/Tree.png'))
  bush = createSprite(150,590,width/100,height,100)
  bush.addImage(loadImage('sprites/Bush (2).png'))
  city = createSprite(465,400)
  city.addImage(loadImage('sprites/City3.png'))
  char1 = createSprite(308,540)
  char1.addImage(loadImage('sprites/char1.png'))
  char2 = createSprite(390,700)
  char2.addImage(loadImage('sprites/char2.png'))
  char3 = createSprite(690,580)
  char3.addImage(loadImage('sprites/char3.png'))
  scene1 = new Group()
  scene2 = new Group()
  scene3 = new Group()
  scene1.add(tree1)
  scene1.add(winterBackground)
  scene1.add(snowman)
  scene1.add(crystal)
  scene2.add(cactus)
  scene2.add(tree2)
  scene2.add(bush)
  scene2.add(desertbg)
  scene3.add(city)
  scene3.add(char1)
  scene3.add(char2)
  scene3.add(char3)
}
function draw() {
  background(0,0,0)
  if (frameCount%300 === 0) {
    currentScene = random([scene1,scene2,scene3])
  } 
  drawSprites(currentScene)
}
