var  winterBackground, tree1, desertbg, cactus, snowman, crystal, tree2, bush, city, char1, char2, char3,winterBackground_2, tree1_2, desertbg_2, cactus_2, snowman_2, crystal_2, tree2_2, bush_2, city_2, char1_2, char2_2, char3_2, scene1, scene2, scene3, scene4, scene5, scene6, currentScene;

function setup() {
  createCanvas(800,800)
  winterBackground = createSprite(755,400)
  winterBackground.addImage(loadImage('sprites/BG1.png'))
  tree1 = createSprite(400,660)
  tree1.addImage(loadImage('sprites/tree_1.png'))
  snowman = createSprite(150,700)
  snowman.addImage(loadImage('sprites/SnowMan.png'))
  crystal = createSprite(660,760)
  crystal.addImage(loadImage('sprites/Crystal.png'))
  desertbg = createSprite(600,400)
  desertbg.addImage(loadImage('sprites/BG.png'))
  cactus = createSprite(310,570)
  cactus.addImage(loadImage('sprites/Cactus1.png'))
  tree2 = createSprite(670,600)
  tree2.addImage(loadImage('sprites/Tree.png'))
  bush = createSprite(150,590)
  bush.addImage(loadImage('sprites/Bush (2).png'))
  city = createSprite(465,400)
  city.addImage(loadImage('sprites/City3.png'))
  char1 = createSprite(308,540)
  char1.addImage(loadImage('sprites/char1.png'))
  char2 = createSprite(390,700)
  char2.addImage(loadImage('sprites/char2.png'))
  char3 = createSprite(690,580)
  char3.addImage(loadImage('sprites/char3.png'))
  winterBackground_2 = createSprite(510,400)
  winterBackground_2.addImage(loadImage('sprites/BG1.png'))
  tree1_2 = createSprite(175,660)
  tree1_2.addImage(loadImage('sprites/tree_1.png'))
  snowman_2 = createSprite(700,700)
  snowman_2.addImage(loadImage('sprites/SnowMan.png'))
  crystal_2 = createSprite(450,760)
  crystal_2.addImage(loadImage('sprites/Crystal.png'))
  desertbg_2 = createSprite(200,400)
  desertbg_2.addImage(loadImage('sprites/BG.png'))
  cactus_2 = createSprite(500,525)
  cactus_2.addImage(loadImage('sprites/Cactus1.png'))
  tree2_2 = createSprite(270,600)
  tree2_2.addImage(loadImage('sprites/Tree.png'))
  bush_2 = createSprite(650,635)
  bush_2.addImage(loadImage('sprites/Bush (2).png'))
  city_2 = createSprite(100,400)
  city_2.addImage(loadImage('sprites/City3.png'))
  char1_2 = createSprite(100,540)
  char1_2.addImage(loadImage('sprites/char1.png'))
  char2_2 = createSprite(65,720)
  char2_2.addImage(loadImage('sprites/char2.png'))
  char3_2 = createSprite(535,565)
  char3_2.addImage(loadImage('sprites/char3.png'))
  scene1 = new Group()
  scene2 = new Group()
  scene3 = new Group()
  scene4 = new Group()
  scene5 = new Group()
  scene6 = new Group()
  scene1.add(tree1)
  scene1.add(winterBackground)
  scene1.add(snowman)
  scene1.add(crystal)
  scene2.add(cactus)
  scene2.add(tree2)
  scene2.add(bush)
  scene2.add(desertbg)
  scene3.add(city)
  scene3.add(char1)
  scene3.add(char2)
  scene3.add(char3)
  scene4.add(tree1_2)
  scene4.add(winterBackground_2)
  scene4.add(snowman_2)
  scene4.add(crystal_2)
  scene5.add(cactus_2)
  scene5.add(bush_2)
  scene5.add(desertbg_2)
  scene5.add(tree2_2)
  scene6.add(city_2)
  scene6.add(char1_2)
  scene6.add(char2_2)
  scene6.add(char3_2)
}
function draw() {
  background(0,0,0)
  if (frameCount%300 === 0) {
    currentScene = random([scene1,scene2,scene3,scene4,scene5,scene6])
  } 
  drawSprites(currentScene)
}
